/*|||||||||||||||||||||||||||||||||
|| 0 * * * * * * * * * ▲ * * * * ||
|| * ||||||||||| * ||||||||||| * ||
|| * ||  * * * * * ||       || 0 ||
|| * ||||||||||| * ||||||||||| * ||
|| * * ▲ * * 0|| * ||   (< * * * ||
|| * ||||||||||| * ||  ||||||||||||
|| * * * * * * * * *   ||||||||||||
| author: CAB |||||||||||||||||||||
| website: github.com/alexcab |||||
| created: 09.08.2026 |||||||||||*/

package planning.engine.planner.mpi.actors.manager

import cats.MonadThrow
import cats.effect.Async
import org.apache.pekko.actor.typed.{ActorRef, ActorSystem, Behavior}
import planning.engine.common.graph.edges.MeKey
import planning.engine.common.values.io.IoValue
import planning.engine.common.values.node.MnId
import planning.engine.common.values.sample.SampleId
import planning.engine.planner.mpi.actors.manager.logic.{Actor, ApiImpl}
import planning.engine.planner.mpi.actors.node.Node
import planning.engine.planner.mpi.common.data.samples.Sample
import planning.engine.planner.mpi.actors.manager.data.Definition
import planning.engine.planner.mpi.actors.visualizer.Visualizer
import planning.engine.planner.mpi.common.data.edge.EdgeData
import planning.engine.planner.mpi.common.data.node.NodeData
import planning.engine.planner.mpi.common.repr.Representable

trait Manager:

  // Add nodes command:
  // - Create  and return new MnId
  // - Spawn new NodeActor with given NodeData and MnId.
  // Used mainly for testing and debugging.
  def addNode[F[_]: Async](data: NodeData)(using ActorSystem[?]): F[MnId]

  // Add edge command:
  // - Lookup source and target node actors by MnId.
  // - Add edge source to source node, and edge target to target node.
  // Failure cases:
  // - If source or target node not found.
  // - If SampleId found, but HnIndex not the same.
  // Used mainly for testing and debugging.
  def addEdge[F[_]: Async](key: MeKey, data: EdgeData)(using ActorSystem[?]): F[MeKey]
  
  // Add manually defined samples command:
  // - Lookup nodes from `nodes` field by name, create new if not found (replacing MnId.Nim ID with Abs or Con).
  // - Create new SampleId for each sample.
  // - Add or update map edges for each sample (using Node.upsertEdgeSrc, where HnIndex created in each node).
  // - Store full sample data in the manager state. And Values in each node state (for speedup probs calculation).
  // - Notify all nodes with new total number of samples (for probs calculation).
  // - Notify visualizer with new map structure (for visualization).
  // All nodes in the `samples` must be in the `nodes` map and have ID of `MnId.Nim` type (it is ok to send
  // all node data in this case, even if they already in the map network, since nodes in manually defined sample
  // anyway have all of them).
  def addManSamples[F[_]: Async](
      samples: Set[Sample.Man],
      nodes: Map[MnId.Nim, NodeData],
  )(using ActorSystem[?]): F[Map[SampleId, Sample.Man]]

  // Add samples, generated by loopback learning algorithm command:
  // - Works same as `addManSamples`, except first step, where instead of looking up nodes by name, 
  //   it just creates all nodes from `newNodes`.
  // - Here `samples` can have mix of `MnId.Nim`, MnId.Abs` and `MnId.Con` IDs. All `MnId.Nim` IDs 
  //   expected to be found in `newNodes` and will be replaced with new `MnId.Abs` or `MnId.Con`.
  def addGenSamples[F[_]: Async](
      samples: Set[Sample.Gen],
      newNodes: Map[MnId.Nim, Option[IoValue]],
  )(using ActorSystem[?]): F[Map[SampleId, Sample.Gen]]

  // Report an error that occurred in a NodeActor.
  // In simple implementation it will terminate the manager actor and all its children nodes actors,
  // but in future it may be extended to support more complex error handling.
  def reportError[F[_]: MonadThrow](source: Node, msg: Option[Representable], err: Throwable): F[Unit]

object Manager:
  type Msg = Actor.Msg

  def spawn[F[_]: MonadThrow](visualizer: Visualizer, make: (Behavior[Msg], String) => ActorRef[Msg]): F[Manager] =
    MonadThrow[F].catchNonFatal(ApiImpl(Actor.spawn(Definition(visualizer), make)))
