/*|||||||||||||||||||||||||||||||||
|| 0 * * * * * * * * * ▲ * * * * ||
|| * ||||||||||| * ||||||||||| * ||
|| * ||  * * * * * ||       || 0 ||
|| * ||||||||||| * ||||||||||| * ||
|| * * ▲ * * 0|| * ||   (< * * * ||
|| * ||||||||||| * ||  ||||||||||||
|| * * * * * * * * *   ||||||||||||
| author: CAB |||||||||||||||||||||
| website: github.com/alexcab |||||
| created: 16-Aug-26 |||||||||||*/

package planning.engine.planner.mpi.common.data.samples

import planning.engine.common.values.sample.SampleId
import Sample.*
import planning.engine.common.graph.edges.MeKey
import planning.engine.common.values.node.HnIndex
import planning.engine.common.values.text.{Description, Name}

// Fully defined sample data, as they will read from map graph.
final case class Sample(
    id: SampleId,
    props: Props,
    info: Info,
    edges: Set[Edge],
)

object Sample:
  final case class Props(probabilityCount: Long, utility: Double)

  final case class Info(name: Name, description: Option[Description])

  final case class Edge(key: MeKey, srcVal: HnIndex, trgVal: HnIndex)

  // Manually defined sample data, in this format they will be loaded from
  // initial/seed map graph, by Python script.
  // Compared to Gen, have additional info field, which can be used map analysis and visualization.
  final case class Man(props: Props, info: Info, edges: Set[MeKey])

  // Sample data generated by loopback learning algorithm.
  final case class Gen(props: Props, edges: Set[MeKey])
